### ISSUE TITLE
Throughput Monitor bar confusion

### ISSUE THREAD

**Issue by ghost** [SebastienGllmt/Anki-Addons#4]
Would you mind expanding on the third bar?
The first is the 5 minute timer.
The second is the estimated time remaining.
What does the third do? For me it shows 0/Random number and stays fixed.

**Comment by SebastienGllmt** [comment]
The third is how many reviews you've made within the timespan. It's compared to the moving average of how many reviews you usually get done. Ex: 5/17 means you've done 5 reviews and you your target goal should be 17 for this timespan.

**Comment by SebastienGllmt** [comment]
I updated the description at https://ankiweb.net/shared/info/826650564 to say which bar color is which
